version: '3.7'

services:
  php-fpm:
    dns:
      - 8.8.8.8
    build:
      context: ./docker/php-fpm
      args:
        - UID=1000
        - GID=1000
    user: "1000:1000"
    ports:
      - "2053:2053"
    volumes:
      - ./:/app:cached
      - ~/.ssh:/home/testproject/.ssh:cached
    working_dir: /app
    networks:
      - test-project
      - main

  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test-project
      - POSTGRES_PASSWORD=test-project
      - POSTGRES_DB=test-project
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data:cached
    networks:
      - test-project
      - main

  nginx:
    image: nginx:1.20-alpine
    working_dir: /app
    volumes:
      - ./public:/app:cached
      - ./docker/nginx/templates:/etc/nginx/templates:cached
    depends_on:
      - php-fpm
    networks:
      reverse-proxy:
      test-project:
      main:
        aliases:
          - localhost
    environment:
      - VIRTUAL_HOST=localhost

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  test-project:
  reverse-proxy:
    external: true
  main:
    external:
      name: network_default